name: Update/Create AWS Secret

on:
  workflow_call:
    inputs:
      secret-name:
        required: true
        type: string
      secret-value:
        required: true
        type: string
      aws-region:
        required: true
        type: string

jobs:
  update-create-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update/Create Secret in AWS Secrets Manager
      run: |
        # Aqui você adiciona o comando/script para criar ou atualizar o segredo
        # Exemplo: aws secretsmanager create-secret --name ${{ inputs.secret-name }} --secret-string ${{ inputs.secret-value }}
