name: Build docker image

on:
  workflow_call:
    inputs:
      aws-creds-role-to-assume:
        required: true
        type: string
        description: Role arn to assume without aws credentials
      aws-region:
        required: true
        type: string
        description: AWS Region
      docker-build-args:
        required: false
        type: string
        description: docker build args
      docker-build-target:
        required: false
        type: string
        description: Docker Image target during build
      docker-build-context:
        required: false
        type: string
        description: Dockerfile dir
        default: '.'
      docker-file-path:
        required: false
        type: string
        description: Dockerfile path
        default: 'Dockerfile'
      docker-tag:
        required: true
        type: string
        description: Tag to be linked on ECR
      ecr-url:
        required: true
        type: string
        description: ECR url to push images
      ecr-repo:
        required: true
        type: string
        description: ECR repository name

    secrets:
      PIP_EXTRA_INDEX_URL:
        required: false
      GH_ACCESS_TOKEN:
        required: false
      REQUIREMENTS:
        required: false
      NEXT_PUBLIC_PORTAL_AFYA_API_BASE_URL:
        required: false
      NEXT_PUBLIC_BFF_AFYA_API_BASE_URL:
        required: false

jobs:

  build:
    runs-on: ubuntu-22.04
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.1.0
        with:
          role-to-assume: ${{ inputs.aws-creds-role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to ECR ${{ inputs.ecr-url }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ecr-url }}

      - name: Build image
        uses: docker/build-push-action@v4.1.0
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ inputs.docker-build-context }}
          target: ${{ inputs.docker-build-target }}
          file: ${{ inputs.docker-file-path }}
          tags: |
            ${{ inputs.ecr-url }}/${{ inputs.ecr-repo }}:latest
            ${{ inputs.ecr-url }}/${{ inputs.ecr-repo }}:${{ inputs.docker-tag }}
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            PIP_EXTRA_INDEX_URL=${{ secrets.PIP_EXTRA_INDEX_URL }}
            REQUIREMENTS=${{ secrets.REQUIREMENTS }}
